@startuml

title Wear
' left to right direction

actor Guest
usecase " Registration of user" as Registration
Guest -> Registration

actor User
usecase "Create plan" as Create_Plan
User ->  Create_Plan
actor Expert
Expert -left-|> User

@enduml