/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 02-май-2020 21:33:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS Table1 CASCADE
;

/* Create Tables */

CREATE TABLE Table1
(
	user_id integer NOT NULL,
	user_name varchar(50) NULL,
	user_data varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Table1 ADD CONSTRAINT PK_Table1
	PRIMARY KEY (user_id)
;
